--
-- PostgreSQL database dump
--

\restrict qjRJ7BDRbvJ5oGzIeoZYWLvm6kl7rVzBUhpdiJIciUM78R7pAoUmVSucCjV28fo

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: borrowers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.borrowers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    ghana_card character varying(255),
    last_name character varying(255) NOT NULL,
    location character varying(255),
    phone character varying(255),
    updated_at timestamp(6) without time zone,
    whatsapp character varying(255)
);


ALTER TABLE public.borrowers OWNER TO postgres;

--
-- Name: borrowers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.borrowers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.borrowers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funding_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funding_accounts (
    id bigint NOT NULL,
    available_balance numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone,
    currency character varying(3) NOT NULL,
    name character varying(255) NOT NULL,
    reserved_balance numeric(19,4) NOT NULL,
    total_balance numeric(19,4) NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint
);


ALTER TABLE public.funding_accounts OWNER TO postgres;

--
-- Name: funding_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funding_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funding_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funding_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funding_transactions (
    id bigint NOT NULL,
    amount numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone,
    note character varying(255),
    type character varying(20) NOT NULL,
    funding_account_id bigint NOT NULL,
    principal_id bigint,
    CONSTRAINT funding_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'ALLOCATION'::character varying, 'RELEASE'::character varying, 'ADJUSTMENT'::character varying])::text[])))
);


ALTER TABLE public.funding_transactions OWNER TO postgres;

--
-- Name: funding_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funding_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funding_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    duration_weeks integer NOT NULL,
    end_date date,
    interest_rate numeric(5,2) NOT NULL,
    interest_type character varying(255),
    outstanding_balance numeric(15,2) NOT NULL,
    principal_amount numeric(15,2) NOT NULL,
    start_date date,
    status character varying(255),
    total_payable numeric(15,2) NOT NULL,
    borrower_id bigint NOT NULL,
    CONSTRAINT loans_interest_type_check CHECK (((interest_type)::text = ANY ((ARRAY['FLAT'::character varying, 'REDUCING'::character varying])::text[]))),
    CONSTRAINT loans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAID'::character varying, 'DEFAULTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.loans OWNER TO postgres;

--
-- Name: loans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: principals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.principals (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.principals OWNER TO postgres;

--
-- Name: principals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.principals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.principals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repayments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repayments (
    id bigint NOT NULL,
    amount_paid numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone,
    payment_date date,
    payment_method character varying(255),
    repayment_status character varying(255),
    updated_at timestamp(6) without time zone,
    loan_id bigint NOT NULL,
    CONSTRAINT repayments_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'TRANSFER'::character varying, 'CARD'::character varying, 'MOBILE_MONEY'::character varying])::text[]))),
    CONSTRAINT repayments_repayment_status_check CHECK (((repayment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'OVERDUE'::character varying, 'PAID'::character varying, 'DEFAULTED'::character varying])::text[])))
);


ALTER TABLE public.repayments OWNER TO postgres;

--
-- Name: repayments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.repayments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repayments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    hashed_password character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'LOAN_OFFICER'::character varying, 'VIEWER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: borrowers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.borrowers (id, created_at, email, first_name, ghana_card, last_name, location, phone, updated_at, whatsapp) FROM stdin;
1	2026-05-02 13:53:25.824534	kenneth@gmail.com	Kenneth	GHA-2342435	Empraim	Kumasi	0541121606	2026-05-02 13:53:25.824789	0541121606
35	2026-05-03 15:41:51.731523	boateng@gmail.com	Boateng	GHA-724861694-5	Kwaku Emmanuel	Kumasi	0593414976	2026-05-16 18:16:44.144243	0593414976
34	2026-05-02 14:25:24.314282	davidkwaku@gmail.com	David	GHA-718573757-9	Kwaku Osei	Kumasi	0501968413	2026-05-16 18:23:17.721823	0501968413
37	2026-05-16 18:29:52.688658	georgeboat@gmail.com	George 	GHA-717562804-0	Boateng	Kumasi	0546617506	2026-05-16 18:29:52.688845	0546617506
38	2026-05-16 18:34:12.065219	bediakoasare@gmail.com	Bediako 	GHA-724915202-6	Asare	Kumasi	0242827870	2026-05-16 18:34:12.06536	0242827870
39	2026-05-16 18:38:15.133348	josephnketia@gamil.com	Joseph 	GHA-004804091-8	Nketia	AK-379-1615 Gyinyase	0539735791	2026-05-16 18:38:15.133524	0539735791
40	2026-05-16 18:40:26.976037	ericoseiowusu@gmail.com	Eric	GHA-718507014-3	Osei Owusu	Kumasi	0244854249	2026-05-16 18:40:26.976148	0244854249
41	2026-05-16 18:48:46.814195	attaduah@gmail.com	Atta 	GHA-	Duah	Kumasi	0242876800	2026-05-16 18:48:46.814319	0242876800
42	2026-06-21 11:41:38.984009	oseiowusu@gmail.com	Osei	GHA-718600115-7	Owusu (Twum)	Kotei (AB 28 Abrankese)	0248106938	2026-06-21 11:59:16.438676	0248106938
36	2026-05-15 23:55:59.791306	sly@gmail.com	Sylvester	GHA-717142802-7	Antwi (Sly)	Kumasi	0246880364	2026-06-21 12:01:18.741654	0246880364
\.


--
-- Data for Name: funding_accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.funding_accounts (id, available_balance, created_at, currency, name, reserved_balance, total_balance, updated_at, version) FROM stdin;
1	2900.0000	2026-05-02 13:52:03.2432	GHS	Main Account	8900.0000	11800.0000	2026-07-04 21:23:39.40226	87
\.


--
-- Data for Name: funding_transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.funding_transactions (id, amount, created_at, note, type, funding_account_id, principal_id) FROM stdin;
1	5000.0000	2026-05-02 13:52:03.255792	Initial deposit	DEPOSIT	1	\N
2	1000.0000	2026-05-02 13:54:56.260054	Allocated to loan 1	ALLOCATION	1	\N
35	1000.0000	2026-05-02 14:25:46.505848	Allocated to loan 34	ALLOCATION	1	\N
36	1000.0000	2026-05-03 15:42:33.213073	Allocated to loan 35	ALLOCATION	1	\N
37	100.0000	2026-05-10 00:24:20.978136	Bediako 5th repayment	DEPOSIT	1	\N
38	400.0000	2026-05-10 00:25:46.152184	Sylvester's last two repayments	DEPOSIT	1	\N
39	100.0000	2026-05-10 09:08:32.090731	Released from loan 34	RELEASE	1	\N
40	100.0000	2026-05-10 09:08:43.676444	Released from loan 35	RELEASE	1	\N
41	100.0000	2026-05-10 23:32:36.795851	George's third repayment	DEPOSIT	1	\N
42	100.0000	2026-05-12 10:19:09.119204	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
43	100.0000	2026-05-12 10:19:11.806093	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
44	300.0000	2026-05-12 10:21:55.759382	Atta's 5th loan repayment	DEPOSIT	1	\N
45	100.0000	2026-05-15 20:05:09.816149	Loan repayment by David Kwaku Frimpong from loan 34	RELEASE	1	\N
46	100.0000	2026-05-15 20:05:47.379798	George's 4th repayment	DEPOSIT	1	\N
47	300.0000	2026-05-15 20:06:29.913019	Eric's 11th repayment	DEPOSIT	1	\N
48	3000.0000	2026-05-15 23:56:44.49932	Allocated to loan 36	ALLOCATION	1	\N
49	100.0000	2026-05-17 14:21:32.084686	Bediako's 6th repayment	DEPOSIT	1	\N
50	100.0000	2026-05-18 12:18:54.65904	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
51	300.0000	2026-05-18 16:59:51.986649	Eric	DEPOSIT	1	\N
52	300.0000	2026-05-23 21:58:31.333187	Loan repayment by Sylvester Antwi from loan 36	RELEASE	1	\N
53	100.0000	2026-05-23 22:01:17.167836	Bediako's 7th Repayment	DEPOSIT	1	\N
54	300.0000	2026-05-25 10:29:52.475128	Atta's 6th Repayment	DEPOSIT	1	\N
55	100.0000	2026-05-25 10:30:43.956888	George's 5th repayment	DEPOSIT	1	\N
56	100.0000	2026-05-25 11:29:40.209518	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
57	100.0000	2026-05-25 11:29:58.536325	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
58	700.0000	2026-05-25 15:15:21.33886	Top up to disburse to Eric	DEPOSIT	1	\N
59	3000.0000	2026-05-25 15:16:07.393389	Allocated to loan 37	ALLOCATION	1	\N
60	100.0000	2026-05-27 08:06:31.263901	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
61	100.0000	2026-05-27 22:34:34.300254	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
62	300.0000	2026-05-30 22:31:32.070806	Loan repayment by Sylvester Antwi from loan 36	RELEASE	1	\N
63	100.0000	2026-05-30 22:32:59.160183	George’s 6th repayment 	DEPOSIT	1	\N
64	100.0000	2026-05-31 13:02:53.478579	Bediako’s 8th Repayment 	DEPOSIT	1	\N
65	300.0000	2026-06-01 08:37:08.126183	Atta's 7th Repayment	DEPOSIT	1	\N
66	300.0000	2026-06-01 11:19:17.97386	Loan repayment by Eric Osei Owusu from loan 37	RELEASE	1	\N
67	100.0000	2026-06-01 12:13:42.762289	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
68	100.0000	2026-06-01 12:13:57.008355	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
69	200.0000	2026-06-01 12:28:51.112146	Joseph's 7th Repayment	DEPOSIT	1	\N
70	100.0000	2026-06-06 15:17:34.147247	Bediako’s 9th Repayment 	DEPOSIT	1	\N
71	100.0000	2026-06-06 17:03:49.951882	George's 7th Repayment	DEPOSIT	1	\N
72	100.0000	2026-06-06 18:14:08.742233	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
73	100.0000	2026-06-06 18:14:11.312116	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
74	300.0000	2026-06-07 09:28:08.436549	Loan repayment by Sylvester Antwi from loan 36	RELEASE	1	\N
75	100.0000	2026-06-08 14:06:24.366467	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
76	100.0000	2026-06-08 14:06:58.935096	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
77	300.0000	2026-06-08 21:28:57.639109	Loan repayment by Eric Osei Owusu from loan 37	RELEASE	1	\N
78	300.0000	2026-06-11 13:07:09.748527	Atta's 8th Repayment	DEPOSIT	1	\N
79	100.0000	2026-06-13 12:44:15.152572	Bediako's 10th Repayment	DEPOSIT	1	\N
80	100.0000	2026-06-13 12:45:31.592986	George's 8th Repayment	DEPOSIT	1	\N
81	300.0000	2026-06-14 14:01:09.197562	Loan repayment by Sylvester Antwi from loan 36	RELEASE	1	\N
82	100.0000	2026-06-15 21:42:05.43888	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
83	100.0000	2026-06-15 21:42:19.343461	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
84	300.0000	2026-06-15 21:43:00.522778	Loan repayment by Eric Osei Owusu from loan 37	RELEASE	1	\N
85	600.0000	2026-06-15 21:44:53.672351	Joseph's 8th, 9th and 10th repayment - 200 each	DEPOSIT	1	\N
86	300.0000	2026-06-17 19:35:55.468043	Atta's 9th Repayment	DEPOSIT	1	\N
87	300.0000	2026-06-21 08:49:04.104392	Loan repayment by Sylvester Antwi from loan 36	RELEASE	1	\N
88	1000.0000	2026-06-21 12:00:00.417208	Allocated to loan 38	ALLOCATION	1	\N
89	100.0000	2026-06-21 15:22:05.500276	Bediako's 11th Repayment	DEPOSIT	1	\N
90	100.0000	2026-06-22 11:53:15.03894	Bediako's 12th Repayment | Last	DEPOSIT	1	\N
91	100.0000	2026-06-22 11:53:40.995992	George's 9th Repayment	DEPOSIT	1	\N
92	300.0000	2026-06-22 20:02:21.701773	Loan repayment by Eric Osei Owusu from loan 37	RELEASE	1	\N
93	2000.0000	2026-06-22 20:03:02.792964	Allocated to loan 39	ALLOCATION	1	\N
94	100.0000	2026-06-23 00:20:36.784163	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
95	100.0000	2026-06-23 15:03:02.019571	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
96	100.0000	2026-06-23 15:03:18.635923	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
97	300.0000	2026-06-25 10:39:35.200947	Atta's 10th Repayment	DEPOSIT	1	\N
98	100.0000	2026-06-25 20:28:56.011918	George's 10th Repayment	DEPOSIT	1	\N
99	200.0000	2026-06-28 13:25:28.987038	Loan repayment by Bediako  Asare from loan 39	RELEASE	1	\N
100	100.0000	2026-06-28 20:14:10.03824	Loan repayment by Osei Owusu (Twum) from loan 38	RELEASE	1	\N
101	300.0000	2026-06-29 18:04:02.786212	Loan repayment by Eric Osei Owusu from loan 37	RELEASE	1	\N
102	100.0000	2026-06-29 18:41:48.224121	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
103	100.0000	2026-06-29 18:42:08.304809	Loan repayment by Boateng Kwaku Emmanuel from loan 35	RELEASE	1	\N
104	200.0000	2026-06-29 18:45:33.499872	Josephs 11th Repayment	DEPOSIT	1	\N
105	300.0000	2026-07-01 10:25:31.204389	Loan repayment by Sylvester Antwi (Sly) from loan 36	RELEASE	1	\N
106	100.0000	2026-07-01 22:45:26.440332	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
107	100.0000	2026-07-01 22:45:28.231345	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
108	100.0000	2026-07-01 22:45:30.113517	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
109	100.0000	2026-07-01 22:45:35.213918	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
110	100.0000	2026-07-01 22:45:43.106862	Loan repayment by Kenneth Empraim from loan 1	RELEASE	1	\N
111	100.0000	2026-07-02 16:47:50.276559	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
112	100.0000	2026-07-02 16:47:51.859769	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
113	100.0000	2026-07-02 16:47:53.678792	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
114	100.0000	2026-07-02 16:48:01.41405	Loan repayment by David Kwaku Osei from loan 34	RELEASE	1	\N
115	300.0000	2026-07-02 17:04:15.841243	Atta's 11th Repayment	DEPOSIT	1	\N
116	2000.0000	2026-07-03 18:38:54.27676	Allocated to loan 40	ALLOCATION	1	\N
117	2000.0000	2026-07-03 18:39:27.073482	Allocated to loan 41	ALLOCATION	1	\N
118	100.0000	2026-07-04 09:53:57.564416	George's 11th Repayment	DEPOSIT	1	\N
119	300.0000	2026-07-04 19:00:32.352486	Atta's 12th Repayment - Last payment	DEPOSIT	1	\N
120	300.0000	2026-07-04 21:23:39.355559	Loan repayment by Sylvester Antwi (Sly) from loan 36	RELEASE	1	\N
\.


--
-- Data for Name: loans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.loans (id, created_at, duration_weeks, end_date, interest_rate, interest_type, outstanding_balance, principal_amount, start_date, status, total_payable, borrower_id) FROM stdin;
39	2026-06-22 20:03:02.782124	12	2026-09-19	20.00	FLAT	2200.00	2000.00	2026-06-27	ACTIVE	2400.00	38
38	2026-06-21 12:00:00.386397	12	2026-09-19	20.00	FLAT	1100.00	1000.00	2026-06-27	ACTIVE	1200.00	42
37	2026-05-25 15:16:07.379081	12	2026-08-22	20.00	FLAT	2100.00	3000.00	2026-05-30	ACTIVE	3600.00	40
35	2026-05-03 15:42:33.176461	12	2026-08-01	20.00	FLAT	400.00	1000.00	2026-05-09	ACTIVE	1200.00	35
1	2026-05-02 13:54:56.23868	12	2026-07-25	20.00	FLAT	0.00	1000.00	2026-05-02	PAID	1200.00	1
34	2026-05-02 14:25:46.461977	12	2026-08-01	20.00	FLAT	0.00	1000.00	2026-05-09	PAID	1200.00	34
40	2026-07-03 18:38:54.243785	12	2026-10-03	20.00	FLAT	2400.00	2000.00	2026-07-11	ACTIVE	2400.00	1
41	2026-07-03 18:39:27.061466	12	2026-10-03	20.00	FLAT	2400.00	2000.00	2026-07-11	ACTIVE	2400.00	34
36	2026-05-15 23:56:44.456715	12	2026-08-15	20.00	FLAT	1500.00	3000.00	2026-05-23	ACTIVE	3600.00	36
\.


--
-- Data for Name: principals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.principals (id, created_at, email, name, phone, updated_at) FROM stdin;
1	2026-05-02 13:49:52.874174	eugeneamo85@gmail.com	Eugene Amo Agyemang	+233547800363	2026-05-02 13:49:52.874516
2	2026-05-02 13:50:55.65374	gideon@gmail.com	Gideon Empraim	0557546761	2026-05-02 13:50:55.654004
\.


--
-- Data for Name: repayments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.repayments (id, amount_paid, created_at, payment_date, payment_method, repayment_status, updated_at, loan_id) FROM stdin;
64	300.00	2026-05-15 23:56:44.535715	2026-07-04	MOBILE_MONEY	PAID	2026-07-04 21:23:39.399746	36
54	100.00	2026-05-03 15:42:33.262343	2026-07-04	MOBILE_MONEY	PENDING	2026-05-03 15:42:33.262365	35
55	100.00	2026-05-03 15:42:33.264419	2026-07-11	MOBILE_MONEY	PENDING	2026-05-03 15:42:33.264472	35
56	100.00	2026-05-03 15:42:33.266488	2026-07-18	MOBILE_MONEY	PENDING	2026-05-03 15:42:33.266509	35
57	100.00	2026-05-03 15:42:33.268489	2026-07-25	MOBILE_MONEY	PENDING	2026-05-03 15:42:33.268513	35
34	100.00	2026-05-02 14:25:46.51514	2026-05-09	MOBILE_MONEY	PAID	2026-05-10 09:08:32.173239	34
46	100.00	2026-05-03 15:42:33.22654	2026-05-09	MOBILE_MONEY	PAID	2026-05-10 09:08:43.687004	35
2	100.00	2026-05-02 13:54:56.274122	2026-05-09	MOBILE_MONEY	PAID	2026-05-12 10:19:09.144783	1
3	100.00	2026-05-02 13:54:56.277575	2026-05-16	MOBILE_MONEY	PAID	2026-05-12 10:19:11.814316	1
35	100.00	2026-05-02 14:25:46.522228	2026-05-16	MOBILE_MONEY	PAID	2026-05-15 20:05:09.837921	34
65	300.00	2026-05-15 23:56:44.536986	2026-07-11	MOBILE_MONEY	PENDING	2026-05-15 23:56:44.536999	36
66	300.00	2026-05-15 23:56:44.540769	2026-07-18	MOBILE_MONEY	PENDING	2026-05-15 23:56:44.54078	36
67	300.00	2026-05-15 23:56:44.543462	2026-07-25	MOBILE_MONEY	PENDING	2026-05-15 23:56:44.543473	36
68	300.00	2026-05-15 23:56:44.54621	2026-08-01	MOBILE_MONEY	PENDING	2026-05-15 23:56:44.546228	36
69	300.00	2026-05-15 23:56:44.550285	2026-08-08	MOBILE_MONEY	PENDING	2026-05-15 23:56:44.550309	36
47	100.00	2026-05-03 15:42:33.232409	2026-05-16	MOBILE_MONEY	PAID	2026-05-18 12:18:54.680443	35
58	300.00	2026-05-15 23:56:44.517919	2026-05-23	MOBILE_MONEY	PAID	2026-05-23 21:58:31.357695	36
36	100.00	2026-05-02 14:25:46.52624	2026-05-23	MOBILE_MONEY	PAID	2026-05-25 11:29:40.262879	34
48	100.00	2026-05-03 15:42:33.236698	2026-05-23	MOBILE_MONEY	PAID	2026-05-25 11:29:58.549766	35
75	300.00	2026-05-25 15:16:07.42987	2026-07-04	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.429898	37
76	300.00	2026-05-25 15:16:07.433711	2026-07-11	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.433734	37
77	300.00	2026-05-25 15:16:07.436496	2026-07-18	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.436516	37
78	300.00	2026-05-25 15:16:07.438911	2026-07-25	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.438947	37
79	300.00	2026-05-25 15:16:07.441041	2026-08-01	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.44106	37
80	300.00	2026-05-25 15:16:07.443056	2026-08-08	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.443076	37
81	300.00	2026-05-25 15:16:07.445509	2026-08-15	MOBILE_MONEY	PENDING	2026-05-25 15:16:07.445533	37
4	100.00	2026-05-02 13:54:56.280886	2026-05-23	MOBILE_MONEY	PAID	2026-05-27 08:06:31.30381	1
5	100.00	2026-05-02 13:54:56.283749	2026-05-30	MOBILE_MONEY	PAID	2026-05-27 22:34:34.353461	1
59	300.00	2026-05-15 23:56:44.523425	2026-05-30	MOBILE_MONEY	PAID	2026-05-30 22:31:32.112363	36
70	300.00	2026-05-25 15:16:07.410336	2026-05-30	MOBILE_MONEY	PAID	2026-06-01 11:19:18.000238	37
37	100.00	2026-05-02 14:25:46.529535	2026-05-30	MOBILE_MONEY	PAID	2026-06-01 12:13:42.780459	34
49	100.00	2026-05-03 15:42:33.241099	2026-05-30	MOBILE_MONEY	PAID	2026-06-01 12:13:57.016399	35
6	100.00	2026-05-02 13:54:56.287953	2026-06-06	MOBILE_MONEY	PAID	2026-06-06 18:14:08.799659	1
7	100.00	2026-05-02 13:54:56.290857	2026-06-13	MOBILE_MONEY	PAID	2026-06-06 18:14:11.320368	1
60	300.00	2026-05-15 23:56:44.527007	2026-06-06	MOBILE_MONEY	PAID	2026-06-07 09:28:08.464065	36
38	100.00	2026-05-02 14:25:46.533466	2026-06-06	MOBILE_MONEY	PAID	2026-06-08 14:06:24.409008	34
50	100.00	2026-05-03 15:42:33.248923	2026-06-06	MOBILE_MONEY	PAID	2026-06-08 14:06:58.943425	35
71	300.00	2026-05-25 15:16:07.414984	2026-06-06	MOBILE_MONEY	PAID	2026-06-08 21:28:57.671058	37
61	300.00	2026-05-15 23:56:44.528705	2026-06-13	MOBILE_MONEY	PAID	2026-06-14 14:01:09.254137	36
39	100.00	2026-05-02 14:25:46.538959	2026-06-13	MOBILE_MONEY	PAID	2026-06-15 21:42:05.494482	34
51	100.00	2026-05-03 15:42:33.254972	2026-06-13	MOBILE_MONEY	PAID	2026-06-15 21:42:19.349517	35
72	300.00	2026-05-25 15:16:07.417838	2026-06-13	MOBILE_MONEY	PAID	2026-06-15 21:43:00.538619	37
62	300.00	2026-05-15 23:56:44.530091	2026-06-20	MOBILE_MONEY	PAID	2026-06-21 08:49:04.145085	36
83	100.00	2026-06-21 12:00:00.445758	2026-07-04	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.445777	38
84	100.00	2026-06-21 12:00:00.451266	2026-07-11	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.451286	38
85	100.00	2026-06-21 12:00:00.454589	2026-07-18	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.454612	38
86	100.00	2026-06-21 12:00:00.457802	2026-07-25	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.457817	38
87	100.00	2026-06-21 12:00:00.461206	2026-08-01	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.461223	38
88	100.00	2026-06-21 12:00:00.464036	2026-08-08	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.46405	38
89	100.00	2026-06-21 12:00:00.465931	2026-08-15	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.465969	38
90	100.00	2026-06-21 12:00:00.467656	2026-08-22	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.467669	38
91	100.00	2026-06-21 12:00:00.469225	2026-08-29	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.469235	38
92	100.00	2026-06-21 12:00:00.475624	2026-09-05	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.475674	38
73	300.00	2026-05-25 15:16:07.42045	2026-06-20	MOBILE_MONEY	PAID	2026-06-22 20:02:21.745988	37
8	100.00	2026-05-02 13:54:56.293177	2026-06-20	MOBILE_MONEY	PAID	2026-06-23 00:20:36.82224	1
40	100.00	2026-05-02 14:25:46.541791	2026-06-20	MOBILE_MONEY	PAID	2026-06-23 15:03:02.060273	34
52	100.00	2026-05-03 15:42:33.258045	2026-06-20	MOBILE_MONEY	PAID	2026-06-23 15:03:18.643239	35
82	100.00	2026-06-21 12:00:00.435793	2026-06-27	MOBILE_MONEY	PAID	2026-06-28 20:14:10.136519	38
74	300.00	2026-05-25 15:16:07.422875	2026-06-27	MOBILE_MONEY	PAID	2026-06-29 18:04:02.819399	37
41	100.00	2026-05-02 14:25:46.543973	2026-06-27	MOBILE_MONEY	PAID	2026-06-29 18:41:48.250593	34
53	100.00	2026-05-03 15:42:33.260184	2026-06-27	MOBILE_MONEY	PAID	2026-06-29 18:42:08.309312	35
63	300.00	2026-05-15 23:56:44.534077	2026-06-27	MOBILE_MONEY	PAID	2026-07-01 10:25:31.368391	36
9	100.00	2026-05-02 13:54:56.295096	2026-06-27	MOBILE_MONEY	PAID	2026-07-01 22:45:26.497469	1
10	100.00	2026-05-02 13:54:56.297055	2026-07-04	MOBILE_MONEY	PAID	2026-07-01 22:45:28.246772	1
11	100.00	2026-05-02 13:54:56.299179	2026-07-11	MOBILE_MONEY	PAID	2026-07-01 22:45:30.125396	1
12	100.00	2026-05-02 13:54:56.301107	2026-07-18	MOBILE_MONEY	PAID	2026-07-01 22:45:35.223982	1
1	100.00	2026-05-02 13:54:56.267366	2026-07-25	MOBILE_MONEY	PAID	2026-07-01 22:45:43.127693	1
42	100.00	2026-05-02 14:25:46.54636	2026-07-04	MOBILE_MONEY	PAID	2026-07-02 16:47:50.319934	34
43	100.00	2026-05-02 14:25:46.549017	2026-07-11	MOBILE_MONEY	PAID	2026-07-02 16:47:51.903428	34
44	100.00	2026-05-02 14:25:46.551351	2026-07-18	MOBILE_MONEY	PAID	2026-07-02 16:47:53.686973	34
45	100.00	2026-05-02 14:25:46.56536	2026-07-25	MOBILE_MONEY	PAID	2026-07-02 16:48:01.424986	34
93	100.00	2026-06-21 12:00:00.482199	2026-09-12	MOBILE_MONEY	PENDING	2026-06-21 12:00:00.482226	38
95	200.00	2026-06-22 20:03:02.797942	2026-07-04	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.797949	39
96	200.00	2026-06-22 20:03:02.79974	2026-07-11	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.799748	39
97	200.00	2026-06-22 20:03:02.800994	2026-07-18	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.800999	39
98	200.00	2026-06-22 20:03:02.802532	2026-07-25	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.80254	39
99	200.00	2026-06-22 20:03:02.804089	2026-08-01	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.804095	39
100	200.00	2026-06-22 20:03:02.805618	2026-08-08	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.805624	39
101	200.00	2026-06-22 20:03:02.806924	2026-08-15	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.806933	39
102	200.00	2026-06-22 20:03:02.808225	2026-08-22	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.808233	39
103	200.00	2026-06-22 20:03:02.809527	2026-08-29	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.809535	39
104	200.00	2026-06-22 20:03:02.810766	2026-09-05	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.810771	39
105	200.00	2026-06-22 20:03:02.811753	2026-09-12	MOBILE_MONEY	PENDING	2026-06-22 20:03:02.811758	39
94	200.00	2026-06-22 20:03:02.795438	2026-06-27	MOBILE_MONEY	PAID	2026-06-28 13:25:29.031582	39
106	200.00	2026-07-03 18:38:54.302099	2026-07-11	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.302131	40
107	200.00	2026-07-03 18:38:54.317789	2026-07-18	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.317816	40
108	200.00	2026-07-03 18:38:54.326469	2026-07-25	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.326524	40
109	200.00	2026-07-03 18:38:54.332706	2026-08-01	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.332745	40
110	200.00	2026-07-03 18:38:54.340298	2026-08-08	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.340338	40
111	200.00	2026-07-03 18:38:54.347204	2026-08-15	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.347226	40
112	200.00	2026-07-03 18:38:54.351658	2026-08-22	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.351682	40
113	200.00	2026-07-03 18:38:54.354033	2026-08-29	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.354044	40
114	200.00	2026-07-03 18:38:54.355776	2026-09-05	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.355787	40
115	200.00	2026-07-03 18:38:54.357797	2026-09-12	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.357807	40
116	200.00	2026-07-03 18:38:54.35935	2026-09-19	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.359373	40
117	200.00	2026-07-03 18:38:54.363176	2026-09-26	MOBILE_MONEY	PENDING	2026-07-03 18:38:54.363193	40
118	200.00	2026-07-03 18:39:27.079088	2026-07-11	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.079106	41
119	200.00	2026-07-03 18:39:27.081744	2026-07-18	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.081756	41
120	200.00	2026-07-03 18:39:27.083569	2026-07-25	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.083579	41
121	200.00	2026-07-03 18:39:27.085586	2026-08-01	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.085597	41
122	200.00	2026-07-03 18:39:27.08712	2026-08-08	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.08713	41
123	200.00	2026-07-03 18:39:27.08892	2026-08-15	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.088931	41
124	200.00	2026-07-03 18:39:27.091471	2026-08-22	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.091486	41
125	200.00	2026-07-03 18:39:27.099744	2026-08-29	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.099776	41
126	200.00	2026-07-03 18:39:27.102466	2026-09-05	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.10248	41
127	200.00	2026-07-03 18:39:27.104142	2026-09-12	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.104151	41
128	200.00	2026-07-03 18:39:27.105297	2026-09-19	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.105309	41
129	200.00	2026-07-03 18:39:27.106558	2026-09-26	MOBILE_MONEY	PENDING	2026-07-03 18:39:27.106564	41
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, active, created_at, email, first_name, hashed_password, last_name, phone, role, updated_at, username) FROM stdin;
\.


--
-- Name: borrowers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.borrowers_id_seq', 42, true);


--
-- Name: funding_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funding_accounts_id_seq', 1, true);


--
-- Name: funding_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funding_transactions_id_seq', 120, true);


--
-- Name: loans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.loans_id_seq', 41, true);


--
-- Name: principals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.principals_id_seq', 2, true);


--
-- Name: repayments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.repayments_id_seq', 129, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: borrowers borrowers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowers
    ADD CONSTRAINT borrowers_pkey PRIMARY KEY (id);


--
-- Name: funding_accounts funding_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_accounts
    ADD CONSTRAINT funding_accounts_pkey PRIMARY KEY (id);


--
-- Name: funding_transactions funding_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_transactions
    ADD CONSTRAINT funding_transactions_pkey PRIMARY KEY (id);


--
-- Name: loans loans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT loans_pkey PRIMARY KEY (id);


--
-- Name: principals principals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.principals
    ADD CONSTRAINT principals_pkey PRIMARY KEY (id);


--
-- Name: repayments repayments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repayments
    ADD CONSTRAINT repayments_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: borrowers ukht682rer8p1t67vs9f0ocm8cs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowers
    ADD CONSTRAINT ukht682rer8p1t67vs9f0ocm8cs UNIQUE (email);


--
-- Name: principals ukkp6em9tgdojymqfihihqvnfet; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.principals
    ADD CONSTRAINT ukkp6em9tgdojymqfihihqvnfet UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: funding_transactions fk3tcu2lte1h5wp54hwa2ypy44r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_transactions
    ADD CONSTRAINT fk3tcu2lte1h5wp54hwa2ypy44r FOREIGN KEY (principal_id) REFERENCES public.principals(id);


--
-- Name: funding_transactions fk8p2v497yrdkg8u35olf0wg7hv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_transactions
    ADD CONSTRAINT fk8p2v497yrdkg8u35olf0wg7hv FOREIGN KEY (funding_account_id) REFERENCES public.funding_accounts(id);


--
-- Name: repayments fkhmj0ie2g9apcos3iihqek6qwj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repayments
    ADD CONSTRAINT fkhmj0ie2g9apcos3iihqek6qwj FOREIGN KEY (loan_id) REFERENCES public.loans(id);


--
-- Name: loans fkoustxijh7c89sbwmtlworwcaw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fkoustxijh7c89sbwmtlworwcaw FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict qjRJ7BDRbvJ5oGzIeoZYWLvm6kl7rVzBUhpdiJIciUM78R7pAoUmVSucCjV28fo

